import { useEffect, useState } from 'react';
import { Alert, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, Stack, TextField, Typography } from '@mui/material';
import { createAthleteGroup, getAthleteGroups, updateAthleteGroup, type AthleteGroup } from '../../api/athleteGroups';
import { PageHeader } from '../../components/common/PageHeader';
export function AthleteGroupsPage() {
  const [items, setItems] = useState<AthleteGroup[]>([]); const [editing, setEditing] = useState<AthleteGroup | null | undefined>(); const [form, setForm] = useState({ name: '', description: '', isActive: true }); const [error, setError] = useState('');
  async function load() { setItems(await getAthleteGroups()); }
  useEffect(() => { getAthleteGroups().then(setItems).catch(() => setError('Unable to load athlete Groups.')); }, []);
  function open(item?: AthleteGroup) { setEditing(item ?? null); setForm(item ? { name: item.name, description: item.description, isActive: item.isActive ?? true } : { name: '', description: '', isActive: true }); }
  async function save() { setError(''); try { if (editing) await updateAthleteGroup(editing.id, form); else await createAthleteGroup(form); setEditing(undefined); await load(); } catch { setError('Unable to save this Group. Use a unique name and include a description.'); } }
  async function toggle(item: AthleteGroup) { await updateAthleteGroup(item.id, { name: item.name, description: item.description, isActive: !item.isActive }); await load(); }
  return <><PageHeader title="Athlete Groups" subtitle="Define the age, experience, or skill Groups families use to classify athletes." />{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Button variant="contained" onClick={() => open()}>Create Group</Button><Stack spacing={2} sx={{ mt: 3 }}>{items.map(item => <Card key={item.id}><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} sx={{ justifyContent: 'space-between', gap: 2 }}><div><Typography variant="h6">{item.name}</Typography><Typography>{item.description}</Typography><Typography color="text.secondary">{item.athleteCount ?? 0} athlete(s) · {item.isActive ? 'Available to families' : 'Archived'}</Typography></div><Stack direction="row"><Button onClick={() => open(item)}>Edit</Button><Button color={item.isActive ? 'warning' : 'success'} onClick={() => toggle(item)}>{item.isActive ? 'Archive' : 'Reactivate'}</Button></Stack></Stack></CardContent></Card>)}</Stack><Dialog open={editing !== undefined} onClose={() => setEditing(undefined)} fullWidth><DialogTitle>{editing ? 'Edit Group' : 'Create Group'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField required label="Group name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/><TextField required multiline minRows={3} label="Description for families" helperText="Explain the intended age, experience, skill level, or coach expectations." value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></Stack></DialogContent><DialogActions><Button onClick={() => setEditing(undefined)}>Cancel</Button><Button variant="contained" disabled={!form.name.trim() || !form.description.trim()} onClick={save}>Save Group</Button></DialogActions></Dialog></>;
}
