import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material';
import { PageHeader } from '../../components/common/PageHeader';
import { http } from '../../api/http';

type Package = { id: string; productName: string; isUnlimited: boolean; sessionsRemaining?: number; expiresOn: string; isExpired: boolean; isPaymentCurrent: boolean };
type Athlete = { id: string; firstName: string; lastName: string; familyName: string; missingRequiredWaivers: number; pendingPurchaseCount: number; usaWrestling?: { status: string; membershipNumber: string; submittedOn: string; expiresOn?: string; isExpired: boolean }; packages: Package[] };
type SessionProduct = { id: string; name: string; price: number; hasUnlimitedSessions: boolean; sessionCount?: number; validityDays: number };
export type AttendanceEntry = { id: string; athleteName: string; familyName: string; productName: string; sessionChange: number; note?: string; createdOn: string; staffEmail?: string; eligibilityOverride: boolean };
export function SessionsPage() {
  const [athletes, setAthletes] = useState<Athlete[]>([]); const [error, setError] = useState(''); const [checking, setChecking] = useState('');
  const [products, setProducts] = useState<SessionProduct[]>([]); const [assigning, setAssigning] = useState<Athlete | null>(null);
  const [attendance, setAttendance] = useState<AttendanceEntry[]>([]);
  const [overriding, setOverriding] = useState<Athlete | null>(null); const [overrideReason, setOverrideReason] = useState('');
  const [grant, setGrant] = useState({ productId: '', grantSource: 'PaidOutsideStripe', activationDate: new Date().toISOString().slice(0, 10), note: '' });
  async function load() { try { const [roster, history] = await Promise.all([http.get<Athlete[]>('/staff/sessions/roster'), http.get<AttendanceEntry[]>('/staff/sessions/attendance')]); setAthletes(roster.data); setAttendance(history.data); } catch { setError('Unable to load session balances.'); } }
  useEffect(() => { http.get<Athlete[]>('/staff/sessions/roster').then(r => setAthletes(r.data)).catch(() => setError('Unable to load session balances.')); }, []);
  useEffect(() => { http.get<SessionProduct[]>('/staff/sessions/products').then(r => setProducts(r.data)).catch(() => setError('Unable to load session products.')); }, []);
  useEffect(() => { http.get<AttendanceEntry[]>('/staff/sessions/attendance').then(r => setAttendance(r.data)).catch(() => setError('Unable to load attendance history.')); }, []);
  async function checkIn(id: string, reason?: string) { setChecking(id); setError(''); try { await http.post(`/staff/sessions/athletes/${id}/check-in`, reason ? { overrideEligibility: true, overrideReason: reason } : {}); setOverriding(null); setOverrideReason(''); await load(); } catch { if (!reason) setOverriding(athletes.find(a => a.id === id) ?? null); setError('Check-in blocked. Review package, waiver, payment, and USA Wrestling eligibility.'); } finally { setChecking(''); } }
  async function assign() { if (!assigning) return; setError(''); try { await http.post(`/staff/sessions/athletes/${assigning.id}/packages`, grant); setAssigning(null); setGrant({ productId: '', grantSource: 'PaidOutsideStripe', activationDate: new Date().toISOString().slice(0, 10), note: '' }); await load(); } catch { setError('Unable to assign this package.'); } }
  return <><PageHeader title="Check-in & session balances" subtitle="Current packages, expiration dates, and manual staff check-in." />{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Stack spacing={2}>{athletes.map(a => { const active = a.packages.filter(p => !p.isExpired && (p.isUnlimited || (p.sessionsRemaining ?? 0) > 0)); const usaStatus = a.usaWrestling?.isExpired ? 'Expired' : (a.usaWrestling?.status ?? 'Not submitted'); const usaColor = usaStatus === 'Current' ? 'success' : usaStatus === 'Pending' ? 'warning' : 'error'; return <Card key={a.id}><CardContent sx={{ display: 'flex', justifyContent: 'space-between', gap: 2 }}><div><Typography variant="h6">{a.firstName} {a.lastName}</Typography><Typography color="text.secondary">{a.familyName}</Typography><Stack direction="row" spacing={1} sx={{ mt: 1, flexWrap: 'wrap', rowGap: 1 }}>{active.map(p => <Chip key={p.id} label={`${p.productName}: ${p.isUnlimited ? 'Unlimited' : `${p.sessionsRemaining} left`} · expires ${new Date(p.expiresOn).toLocaleDateString()}`} />)}{active.length === 0 && <Chip color="warning" label={a.pendingPurchaseCount > 0 ? `${a.pendingPurchaseCount} payment(s) pending — no active package` : 'No active package'} />}{a.missingRequiredWaivers > 0 && <Chip color="error" label={`${a.missingRequiredWaivers} waiver(s) missing`}/>}<Chip color={usaColor} label={`USA Wrestling: ${usaStatus}${a.usaWrestling?.membershipNumber ? ` · ${a.usaWrestling.membershipNumber}` : ''}`} /></Stack></div><Stack spacing={1}><Button color={a.missingRequiredWaivers > 0 ? 'warning' : 'primary'} variant="contained" disabled={checking === a.id || active.length === 0} onClick={() => a.missingRequiredWaivers > 0 ? setOverriding(a) : checkIn(a.id)}>{a.missingRequiredWaivers > 0 ? 'Override check-in' : 'Check in'}</Button><Button onClick={() => setAssigning(a)}>Assign package</Button></Stack></CardContent></Card>; })}</Stack>
    <AttendanceList entries={attendance.slice(0, 25)} title="Recent attendance" />
    <Dialog open={!!assigning} onClose={() => setAssigning(null)} fullWidth><DialogTitle>Assign package to {assigning?.firstName} {assigning?.lastName}</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><FormControl required><InputLabel>Session package</InputLabel><Select label="Session package" value={grant.productId} onChange={e => setGrant({ ...grant, productId: e.target.value })}>{products.map(p => <MenuItem key={p.id} value={p.id}>{p.name} — ${p.price.toFixed(2)} — {p.hasUnlimitedSessions ? 'Unlimited' : `${p.sessionCount} sessions`} / {p.validityDays} days</MenuItem>)}</Select></FormControl><FormControl required><InputLabel>Assignment type</InputLabel><Select label="Assignment type" value={grant.grantSource} onChange={e => setGrant({ ...grant, grantSource: e.target.value })}><MenuItem value="PaidOutsideStripe">Paid outside Stripe</MenuItem><MenuItem value="Complimentary">Complimentary</MenuItem></Select></FormControl><TextField required type="date" label="Activation date" slotProps={{ inputLabel: { shrink: true } }} value={grant.activationDate} onChange={e => setGrant({ ...grant, activationDate: e.target.value })}/><TextField label="Note" value={grant.note} onChange={e => setGrant({ ...grant, note: e.target.value })}/></Stack></DialogContent><DialogActions><Button onClick={() => setAssigning(null)}>Cancel</Button><Button variant="contained" disabled={!grant.productId} onClick={assign}>Assign package</Button></DialogActions></Dialog>
    <Dialog open={!!overriding} onClose={() => setOverriding(null)}><DialogTitle>Override eligibility</DialogTitle><DialogContent><Alert severity="warning" sx={{ mb: 2 }}>{overriding?.firstName} does not meet every waiver, payment, or USA Wrestling requirement.</Alert><TextField fullWidth required label="Override reason" value={overrideReason} onChange={e => setOverrideReason(e.target.value)}/></DialogContent><DialogActions><Button onClick={() => setOverriding(null)}>Cancel</Button><Button color="warning" variant="contained" disabled={!overrideReason.trim() || !overriding} onClick={() => overriding && checkIn(overriding.id, overrideReason)}>Override and check in</Button></DialogActions></Dialog></>;
}

export function AttendanceList({ entries, title }: { entries: AttendanceEntry[]; title: string }) { return <Card sx={{ mt: 4 }}><CardContent><Typography variant="h5" sx={{ mb: 2 }}>{title}</Typography><Stack spacing={2}>{entries.map(entry => <Box key={entry.id}><Stack direction={{ xs: 'column', sm: 'row' }} sx={{ justifyContent: 'space-between' }}><div><Typography sx={{ fontWeight: 700 }}>{entry.athleteName} · {entry.familyName}</Typography><Typography color="text.secondary">{entry.productName} · {new Date(entry.createdOn).toLocaleString()} · Staff: {entry.staffEmail ?? 'Unknown'}</Typography>{entry.note && <Typography color="text.secondary">{entry.note}</Typography>}</div>{entry.eligibilityOverride && <Chip color="warning" label="Eligibility override" />}</Stack></Box>)}</Stack>{entries.length === 0 && <Typography color="text.secondary">No check-ins recorded yet.</Typography>}</CardContent></Card>; }
