<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Reference Include="LegacyOS.Api">
      <HintPath>..\LegacyOS.Api\bin\Debug\net10.0\LegacyOS.Api.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
