import { useEffect, useState, type FormEvent } from 'react';
import { Alert, Button, Card, CardContent, Container, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import { http } from '../../api/http';
import { useAuth } from '../../features/auth/AuthContext';

type Organization = { id: string; name: string };
export function SelfRegistrationPage() {
  const auth = useAuth(); const navigate = useNavigate(); const [organizations, setOrganizations] = useState<Organization[]>([]);
  const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  const [form, setForm] = useState({ familyName: '', guardianFirstName: '', guardianLastName: '', email: '', phone: '', password: '', organizationId: '', athleteFirstName: '', athleteLastName: '', dateOfBirth: '', gender: '' });
  useEffect(() => { http.get<Organization[]>('/portal/auth/registration-options').then(r => setOrganizations(r.data)).catch(() => setError('Unable to load registration options.')); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); setSubmitting(true); setError(''); try { await auth.selfRegister({ familyName: form.familyName, guardianFirstName: form.guardianFirstName, guardianLastName: form.guardianLastName, email: form.email, phone: form.phone, password: form.password, organizationId: form.organizationId, athletes: [{ firstName: form.athleteFirstName, lastName: form.athleteLastName, dateOfBirth: form.dateOfBirth, gender: form.gender }] }); navigate('/portal', { replace: true }); } catch { setError('Unable to create your family account. Check the information or try signing in.'); } finally { setSubmitting(false); } }
  return <Container maxWidth="sm" sx={{ py: 6 }}><Card><CardContent sx={{ p: 4 }}><Typography variant="h4">Register your family</Typography><Typography color="text.secondary" sx={{ my: 2 }}>Create your secure account, add an athlete, then choose a package.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Stack component="form" spacing={2} onSubmit={submit}><TextField required label="Family name" value={form.familyName} onChange={e => setForm({ ...form, familyName: e.target.value })}/><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField required fullWidth label="Guardian first name" value={form.guardianFirstName} onChange={e => setForm({ ...form, guardianFirstName: e.target.value })}/><TextField required fullWidth label="Guardian last name" value={form.guardianLastName} onChange={e => setForm({ ...form, guardianLastName: e.target.value })}/></Stack>
      <TextField required type="email" label="Email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><TextField required label="Phone" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/><TextField required type="password" label="Password" helperText="At least 12 characters" slotProps={{ htmlInput: { minLength: 12 } }} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/>
      <FormControl required><InputLabel>Organization</InputLabel><Select label="Organization" value={form.organizationId} onChange={e => setForm({ ...form, organizationId: e.target.value })}>{organizations.map(o => <MenuItem key={o.id} value={o.id}>{o.name}</MenuItem>)}</Select></FormControl><Typography variant="h6">Athlete</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField required fullWidth label="First name" value={form.athleteFirstName} onChange={e => setForm({ ...form, athleteFirstName: e.target.value })}/><TextField required fullWidth label="Last name" value={form.athleteLastName} onChange={e => setForm({ ...form, athleteLastName: e.target.value })}/></Stack><TextField required type="date" label="Date of birth" slotProps={{ inputLabel: { shrink: true } }} value={form.dateOfBirth} onChange={e => setForm({ ...form, dateOfBirth: e.target.value })}/><TextField label="Gender" value={form.gender} onChange={e => setForm({ ...form, gender: e.target.value })}/><Button type="submit" size="large" variant="contained" disabled={submitting}>Create account</Button><Button onClick={() => navigate('/portal/login')}>Already registered? Sign in</Button></Stack>
  </CardContent></Card></Container>;
}
