import { useEffect, useState, type FormEvent } from 'react';
import { Alert, Box, Button, Card, CardContent, Checkbox, Container, FormControl, FormControlLabel, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import { http } from '../../api/http';
import { useAuth } from '../../features/auth/AuthContext';

type Waiver = { id: string; name: string; version: number; fileName: string; isRequired: boolean };
type AthleteGroup = { id: string; name: string; description: string };
export function SelfRegistrationPage() {
  const auth = useAuth(); const navigate = useNavigate(); const [waivers, setWaivers] = useState<Waiver[]>([]); const [groups, setGroups] = useState<AthleteGroup[]>([]);
  const [accepted, setAccepted] = useState<string[]>([]); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  const [form, setForm] = useState({ familyName: '', guardianFirstName: '', guardianLastName: '', email: '', phone: '', password: '', signedName: '', athleteFirstName: '', athleteLastName: '', dateOfBirth: '', gender: '', athleteGroupId: '' });
  useEffect(() => { http.get<{ waivers: Waiver[]; athleteGroups: AthleteGroup[] }>('/portal/auth/registration-options').then(r => { setWaivers(r.data.waivers); setGroups(r.data.athleteGroups); }).catch(() => setError('Unable to load registration requirements.')); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); setSubmitting(true); setError(''); try { await auth.selfRegister({ familyName: form.familyName, guardianFirstName: form.guardianFirstName, guardianLastName: form.guardianLastName, email: form.email, phone: form.phone, password: form.password, signedName: form.signedName, acceptedWaiverIds: accepted, athletes: [{ firstName: form.athleteFirstName, lastName: form.athleteLastName, dateOfBirth: form.dateOfBirth, gender: form.gender, athleteGroupId: form.athleteGroupId }] }); navigate('/portal', { replace: true }); } catch (reason) { const apiError = reason as { response?: { status?: number; data?: { message?: string } } }; setError(apiError.response?.status === 409 ? 'An account already uses this email. Sign in or use Forgot password instead.' : apiError.response?.data?.message ?? 'Unable to create your family account. Complete every required field and waiver.'); } finally { setSubmitting(false); } }
  const requiredComplete = waivers.filter(w => w.isRequired).every(w => accepted.includes(w.id));
  return <Container maxWidth="sm" sx={{ py: 6 }}><Card><CardContent sx={{ p: 4 }}><Typography variant="h4">Register your family</Typography><Typography color="text.secondary" sx={{ my: 2 }}>Create your account, add an athlete, accept required waivers, then choose a product.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Stack component="form" spacing={2} onSubmit={submit}><TextField required label="Family name" value={form.familyName} onChange={e => setForm({ ...form, familyName: e.target.value })}/><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField required fullWidth label="Guardian first name" value={form.guardianFirstName} onChange={e => setForm({ ...form, guardianFirstName: e.target.value })}/><TextField required fullWidth label="Guardian last name" value={form.guardianLastName} onChange={e => setForm({ ...form, guardianLastName: e.target.value })}/></Stack>
      <TextField required type="email" label="Email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><TextField required label="Phone" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/><TextField required type="password" label="Password" helperText="At least 12 characters" slotProps={{ htmlInput: { minLength: 12 } }} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/>
      <Typography variant="h6">Athlete</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField required fullWidth label="First name" value={form.athleteFirstName} onChange={e => setForm({ ...form, athleteFirstName: e.target.value })}/><TextField required fullWidth label="Last name" value={form.athleteLastName} onChange={e => setForm({ ...form, athleteLastName: e.target.value })}/></Stack><TextField required type="date" label="Date of birth" slotProps={{ inputLabel: { shrink: true } }} value={form.dateOfBirth} onChange={e => setForm({ ...form, dateOfBirth: e.target.value })}/><TextField label="Gender" value={form.gender} onChange={e => setForm({ ...form, gender: e.target.value })}/><FormControl required fullWidth><InputLabel>Group</InputLabel><Select label="Group" value={form.athleteGroupId} onChange={e => setForm({ ...form, athleteGroupId: e.target.value })}>{groups.map(group => <MenuItem key={group.id} value={group.id}><Box><Typography>{group.name}</Typography><Typography variant="caption" color="text.secondary">{group.description}</Typography></Box></MenuItem>)}</Select></FormControl>{groups.length === 0 && <Alert severity="warning">Registration is unavailable until an administrator creates an Athlete Group.</Alert>}
      {waivers.length === 0 && <Alert severity="info">No waivers are currently required.</Alert>}
      {waivers.length > 0 && <><Typography variant="h6">Required waivers</Typography>{waivers.map(w => <Card variant="outlined" key={w.id}><CardContent><Typography sx={{ fontWeight: 700 }}>{w.name} · Version {w.version}</Typography><Button href={`${import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:5021'}/portal/auth/waivers/${w.id}/file`} target="_blank">Review PDF</Button><FormControlLabel control={<Checkbox checked={accepted.includes(w.id)} onChange={e => setAccepted(current => e.target.checked ? [...current, w.id] : current.filter(id => id !== w.id))}/>} label={`I agree to this waiver for ${form.athleteFirstName || 'the athlete'}.`}/></CardContent></Card>)}<TextField required label="Type your full legal name" value={form.signedName} onChange={e => setForm({ ...form, signedName: e.target.value })} helperText="Your electronic signature is valid for 365 days."/></>}
      <Button type="submit" size="large" variant="contained" disabled={submitting || !form.athleteGroupId || !requiredComplete || (waivers.length > 0 && !form.signedName.trim())}>Create account</Button><Button onClick={() => navigate('/portal/login')}>Already registered? Sign in</Button></Stack>
  </CardContent></Card></Container>;
}
