import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import Grid from '@mui/material/Grid';
import { useNavigate, useParams } from 'react-router-dom';
import { PageHeader } from '../../components/common/PageHeader';
import { getFamily, getFamilyOrders, reconcileOrder, refundOrder, resetParentPassword, saveAthlete, sendParentInvitation, setFamilyArchived, updateFamily, updateGuardian, type AthleteInput, type FamilyDetail, type HistoricalOrder } from '../../api/families';
import { getFamilyWaivers, openStaffWaiver, type StaffWaiver } from '../../api/waivers';
import { http } from '../../api/http';
import { AttendanceList, type AttendanceEntry } from '../Sessions/SessionsPage';

export function FamilyDetailPage() {
  const { familyId } = useParams(); const navigate = useNavigate(); const [family, setFamily] = useState<FamilyDetail | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [tab, setTab] = useState(0);
  const [familyEdit, setFamilyEdit] = useState(false); const [guardianEdit, setGuardianEdit] = useState<FamilyDetail['guardians'][number] | null>(null);
  const [athleteEdit, setAthleteEdit] = useState<FamilyDetail['athletes'][number] | null | undefined>();
  const [inviteMessage, setInviteMessage] = useState('');
  const [resetGuardian, setResetGuardian] = useState<FamilyDetail['guardians'][number] | null>(null); const [temporaryPassword, setTemporaryPassword] = useState('');
  async function load() { if (!familyId) return; setFamily(await getFamily(familyId)); }
  useEffect(() => { if (familyId) getFamily(familyId).then(setFamily).catch(() => setError('Unable to load this family.')).finally(() => setLoading(false)); }, [familyId]);
  if (!familyId) return <Alert severity="error">Family id was not provided.</Alert>; if (loading) return <CircularProgress />; if (error || !family) return <Alert severity="error">{error || 'Family not found.'}</Alert>;
  async function archive(currentFamily: FamilyDetail) { if (!window.confirm(`${currentFamily.isActive ? 'Archive' : 'Restore'} this family? ${currentFamily.isActive ? 'Parent access will be disabled, but all history will be preserved.' : 'Parent access will be restored.'}`)) return; await setFamilyArchived(currentFamily.id, currentFamily.isActive); await load(); }
  return <><PageHeader title={family.familyName} subtitle="Family administration" action={<Stack direction="row" spacing={1}><Button variant="outlined" onClick={() => navigate('/families')}>Back</Button><Button variant="outlined" onClick={() => setFamilyEdit(true)}>Edit family</Button><Button color={family.isActive ? 'warning' : 'success'} variant="outlined" onClick={() => archive(family)}>{family.isActive ? 'Archive family' : 'Restore family'}</Button><Button variant="contained" onClick={() => setAthleteEdit(null)}>Add athlete</Button></Stack>}/>
    <Grid container spacing={2} sx={{ mb: 3 }}><Grid size={{ xs: 12, md: 3 }}><StatCard label="Athletes" value={String(family.athletes.length)}/></Grid><Grid size={{ xs: 12, md: 3 }}><StatCard label="Guardians" value={String(family.guardians.length)}/></Grid><Grid size={{ xs: 12, md: 3 }}><StatCard label="Unsigned waivers" value={String(family.athletes.reduce((n, a) => n + (a.missingRequiredWaivers ?? 0), 0))}/></Grid><Grid size={{ xs: 12, md: 3 }}><StatCard label="Status" value={family.isActive ? 'Active' : 'Inactive'}/></Grid></Grid>
    <Card><CardContent>{inviteMessage && <Alert severity={inviteMessage.startsWith('Unable') ? 'error' : 'success'} sx={{ mb: 2 }}>{inviteMessage}</Alert>}<Tabs value={tab} onChange={(_, value) => setTab(value)} sx={{ mb: 3 }}><Tab label="Overview"/><Tab label="Athletes"/><Tab label="Packages"/><Tab label="Orders"/><Tab label="Attendance"/><Tab label="Documents"/></Tabs>
      {tab === 0 && <Section title="Guardians">{family.guardians.map(g => <Box key={g.id} sx={{ mb: 2 }}><Stack direction="row" sx={{ justifyContent: 'space-between' }}><div><Typography sx={{ fontWeight: 700 }}>{g.firstName} {g.lastName}{g.isPrimaryContact && <Chip size="small" label="Primary" sx={{ ml: 1 }}/>}</Typography><Typography color="text.secondary">{g.email} · {g.phone}</Typography></div><Stack direction="row" spacing={1}><Button onClick={async () => { setInviteMessage(''); try { const result = await sendParentInvitation(g.id); setInviteMessage(result.message); } catch { setInviteMessage('Unable to send invitation. The guardian may already have an account, or email delivery is not configured.'); } }}>Send parent invitation</Button><Button onClick={() => { setTemporaryPassword(''); setResetGuardian(g); }}>Reset parent password</Button><Button onClick={() => setGuardianEdit(g)}>Edit</Button></Stack></Stack></Box>)}</Section>}
      {tab === 1 && <Stack spacing={2}>{family.athletes.map(a => <Card variant="outlined" key={a.id}><CardContent><Stack direction="row" sx={{ justifyContent: 'space-between' }}><div><Typography variant="h6">{a.firstName} {a.lastName}</Typography><Typography color="text.secondary">DOB {a.dateOfBirth}{a.gender ? ` · ${a.gender}` : ''}</Typography><Chip sx={{ mt: 1 }} color={(a.missingRequiredWaivers ?? 0) > 0 ? 'warning' : 'success'} label={(a.missingRequiredWaivers ?? 0) > 0 ? `${a.missingRequiredWaivers} waiver(s) missing` : 'Waivers current'}/></div><Button onClick={() => setAthleteEdit(a)}>Edit</Button></Stack></CardContent></Card>)}</Stack>}
      {tab === 2 && <Stack spacing={2}>{family.athletes.map(a => <Box key={a.id}><Typography variant="h6">{a.firstName} {a.lastName}</Typography>{(a.sessionPackages ?? []).map(p => <Chip key={p.id} sx={{ mr: 1, mt: 1 }} label={`${p.productName}: ${p.isUnlimited ? 'Unlimited' : `${p.sessionsRemaining} remaining`} · expires ${new Date(p.expiresOn).toLocaleDateString()}`}/>) }{(a.sessionPackages ?? []).length === 0 && <Typography color="text.secondary">No assigned packages</Typography>}</Box>)}</Stack>}
      {tab === 3 && <Orders familyId={family.id}/>} {tab === 4 && <FamilyAttendance familyId={family.id}/>} {tab === 5 && <Documents family={family}/>}</CardContent></Card>
    <FamilyDialog open={familyEdit} family={family} close={() => setFamilyEdit(false)} saved={async value => { await updateFamily(family.id, value); setFamilyEdit(false); await load(); }}/>
    <GuardianDialog key={guardianEdit?.id ?? 'none'} guardian={guardianEdit} close={() => setGuardianEdit(null)} saved={async value => { if (guardianEdit) await updateGuardian(family.id, guardianEdit.id, value); setGuardianEdit(null); await load(); }}/>
    <AthleteDialog key={athleteEdit?.id ?? (athleteEdit === null ? 'new' : 'closed')} athlete={athleteEdit} close={() => setAthleteEdit(undefined)} saved={async value => { await saveAthlete(family.id, value, athleteEdit?.id); setAthleteEdit(undefined); await load(); }}/>
    <Dialog open={resetGuardian !== null} onClose={() => setResetGuardian(null)} fullWidth><DialogTitle>Reset parent password</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><Typography>Set a temporary password for {resetGuardian?.email}. Existing sessions will be signed out.</Typography><TextField type="password" label="Temporary password" helperText="At least 12 characters" value={temporaryPassword} onChange={e => setTemporaryPassword(e.target.value)}/></Stack></DialogContent><DialogActions><Button onClick={() => setResetGuardian(null)}>Cancel</Button><Button variant="contained" disabled={temporaryPassword.length < 12} onClick={async () => { if (!resetGuardian) return; setInviteMessage(''); try { await resetParentPassword(resetGuardian.id, temporaryPassword); setResetGuardian(null); setTemporaryPassword(''); setInviteMessage('Parent password reset. Share the temporary password securely.'); } catch { setResetGuardian(null); setInviteMessage('Unable to reset password. This guardian may need a parent invitation first.'); } }}>Reset password</Button></DialogActions></Dialog></>;
}

function Orders({ familyId }: { familyId: string }) {
  const [orders, setOrders] = useState<HistoricalOrder[]>([]); const [message, setMessage] = useState('');
  const [refunding, setRefunding] = useState<HistoricalOrder | null>(null); const [reason, setReason] = useState('');
  const [saving, setSaving] = useState(false); const [refundError, setRefundError] = useState('');
  const load = () => getFamilyOrders(familyId).then(setOrders);
  useEffect(() => { getFamilyOrders(familyId).then(setOrders); }, [familyId]);
  async function reconcile(id: string) { const result = await reconcileOrder(id); setMessage(result.status === 'Completed' ? 'Stripe payment confirmed and package activated.' : `Stripe reports ${result.paymentStatus ?? result.status}; the package is not active yet.`); await load(); }
  async function refund() { if (!refunding || !reason.trim()) return; setSaving(true); setRefundError(''); try { await refundOrder(refunding.id, reason); setRefunding(null); setReason(''); setMessage('Refund completed, future installments canceled, and package deactivated.'); await load(); } catch { setRefundError('Unable to complete the refund. Confirm the API is restarted and review Stripe for this payment.'); } finally { setSaving(false); } }
  return <><Stack spacing={2}>{message && <Alert severity="info">{message}</Alert>}{orders.map(o => { const item = JSON.parse(o.itemSnapshotJson) as { Name?: string; name?: string }; const athlete = o.athleteSnapshotJson ? JSON.parse(o.athleteSnapshotJson) as { FirstName?: string; firstName?: string; LastName?: string; lastName?: string } : null; return <Card variant="outlined" key={o.id}><CardContent><Stack direction="row" sx={{ justifyContent: 'space-between' }}><div><Typography variant="h6">{item.Name ?? item.name ?? o.kind}</Typography><Typography color="text.secondary">{athlete ? `${athlete.FirstName ?? athlete.firstName} ${athlete.LastName ?? athlete.lastName} · ` : ''}{new Date(o.createdOn).toLocaleDateString()} · {o.status}</Typography><Typography>${o.originalAmount.toFixed(2)}{o.discountAmount > 0 ? ` − $${o.discountAmount.toFixed(2)} (${o.discountCodeSnapshot})` : ''} = ${o.amount.toFixed(2)}</Typography></div><Stack>{o.status === 'Pending' && <Button onClick={() => reconcile(o.id)}>Check Stripe status</Button>}{o.status === 'Completed' && <Button color="error" onClick={() => { setRefunding(o); setRefundError(''); }}>Refund / cancel</Button>}</Stack></Stack></CardContent></Card>; })}{orders.length === 0 && <Typography color="text.secondary">No orders recorded.</Typography>}</Stack>
    <Dialog open={!!refunding} onClose={() => !saving && setRefunding(null)} fullWidth><DialogTitle>Refund and deactivate package</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}>{refundError && <Alert severity="error">{refundError}</Alert>}<Alert severity="warning">This refunds the collected Stripe payment, cancels future installments, and removes package access. Attendance and order history remain.</Alert><TextField required multiline minRows={2} label="Refund reason" value={reason} onChange={e => setReason(e.target.value)} /></Stack></DialogContent><DialogActions><Button disabled={saving} onClick={() => setRefunding(null)}>Cancel</Button><Button color="error" variant="contained" disabled={saving || !reason.trim()} onClick={refund}>{saving ? 'Processing…' : 'Confirm refund'}</Button></DialogActions></Dialog></>;
}

function FamilyAttendance({ familyId }: { familyId: string }) { const [entries, setEntries] = useState<AttendanceEntry[]>([]); const [error, setError] = useState(''); useEffect(() => { http.get<AttendanceEntry[]>('/staff/sessions/attendance', { params: { familyId } }).then(r => setEntries(r.data)).catch(() => setError('Unable to load attendance history.')); }, [familyId]); return <>{error && <Alert severity="error">{error}</Alert>}<AttendanceList entries={entries} title="Family attendance" /></>; }

function Documents({ family }: { family: FamilyDetail }) {
  const [waivers, setWaivers] = useState<StaffWaiver[]>([]); const [error, setError] = useState('');
  useEffect(() => { getFamilyWaivers(family.id).then(setWaivers).catch(() => setError('Unable to load waivers.')); }, [family.id]);
  return <>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Alert severity="info" sx={{ mb: 2 }}>Waiver templates are managed globally from the Waivers page. This tab shows this family's signatures.</Alert><Stack spacing={2}>{waivers.map(w => <Card variant="outlined" key={w.id}><CardContent><Stack direction="row" sx={{ justifyContent: 'space-between' }}><div><Typography variant="h6">{w.name} · Version {w.version}</Typography><Typography color="text.secondary">{w.isActive ? 'Active' : 'Archived'} · {w.isRequired ? 'Required' : 'Optional'}</Typography><Typography color="text.secondary">{w.signatures.length} signed: {w.signatures.map(s => `${s.athleteName} (${new Date(s.signedOn).toLocaleDateString()})`).join(', ') || 'none'}</Typography></div><Button onClick={() => openStaffWaiver(w.id, w.fileName)}>View PDF</Button></Stack></CardContent></Card>)}</Stack></>;
}

function FamilyDialog({ open, family, close, saved }: { open: boolean; family: FamilyDetail; close: () => void; saved: (v: { familyName: string; isActive: boolean }) => Promise<void> }) { const [name, setName] = useState(family.familyName); return <Dialog open={open} onClose={close}><DialogTitle>Edit family</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField label="Family name" value={name} onChange={e => setName(e.target.value)}/></Stack></DialogContent><DialogActions><Button onClick={close}>Cancel</Button><Button onClick={() => saved({ familyName: name, isActive: family.isActive })}>Save</Button></DialogActions></Dialog>; }
function GuardianDialog({ guardian, close, saved }: { guardian: FamilyDetail['guardians'][number] | null; close: () => void; saved: (v: Omit<FamilyDetail['guardians'][number], 'id'>) => Promise<void> }) { const [v, setV] = useState(guardian); if (!v) return null; return <Dialog open onClose={close}><DialogTitle>Edit guardian</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField label="First name" value={v.firstName} onChange={e => setV({ ...v, firstName: e.target.value })}/><TextField label="Last name" value={v.lastName} onChange={e => setV({ ...v, lastName: e.target.value })}/><TextField label="Email" value={v.email} onChange={e => setV({ ...v, email: e.target.value })}/><TextField label="Phone" value={v.phone} onChange={e => setV({ ...v, phone: e.target.value })}/></Stack></DialogContent><DialogActions><Button onClick={close}>Cancel</Button><Button onClick={() => saved(v)}>Save</Button></DialogActions></Dialog>; }
function AthleteDialog({ athlete, close, saved }: { athlete: FamilyDetail['athletes'][number] | null | undefined; close: () => void; saved: (v: AthleteInput) => Promise<void> }) { const [v, setV] = useState<AthleteInput>(athlete ? { firstName: athlete.firstName, lastName: athlete.lastName, dateOfBirth: athlete.dateOfBirth, gender: athlete.gender } : { firstName: '', lastName: '', dateOfBirth: '', gender: '' }); return <Dialog open={athlete !== undefined} onClose={close}><DialogTitle>{athlete ? 'Edit athlete' : 'Add athlete'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><TextField label="First name" value={v.firstName} onChange={e => setV({ ...v, firstName: e.target.value })}/><TextField label="Last name" value={v.lastName} onChange={e => setV({ ...v, lastName: e.target.value })}/><TextField type="date" label="Date of birth" slotProps={{ inputLabel: { shrink: true } }} value={v.dateOfBirth} onChange={e => setV({ ...v, dateOfBirth: e.target.value })}/><TextField label="Gender" value={v.gender} onChange={e => setV({ ...v, gender: e.target.value })}/></Stack></DialogContent><DialogActions><Button onClick={close}>Cancel</Button><Button onClick={() => saved(v)}>Save</Button></DialogActions></Dialog>; }
function StatCard({ label, value }: { label: string; value: string }) { return <Card><CardContent><Typography color="text.secondary" variant="body2">{label}</Typography><Typography variant="h5" sx={{ mt: 1, fontWeight: 800 }}>{value}</Typography></CardContent></Card>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <Box><Typography variant="h6">{title}</Typography><Divider sx={{ my: 2 }}/>{children}</Box>; }
