import { useEffect, useState } from 'react';
import { Alert, Button, Card, CardContent, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material';
import { PageHeader } from '../../components/common/PageHeader';
import { http } from '../../api/http';
type Organization = { id: string; name: string }; type Service = { id: string; name: string; shortName: string; organizationId: string; organizationName: string; isActive: boolean };
export function ServicesPage() {
  const [data, setData] = useState<{ organizations: Organization[]; services: Service[] }>({ organizations: [], services: [] }); const [editing, setEditing] = useState<Service | null | undefined>(); const [error, setError] = useState('');
  const [form, setForm] = useState({ organizationId: '', name: '', shortName: '', isActive: true });
  async function load() { try { setData((await http.get('/membership-plans/admin-catalog')).data); } catch { setError('Unable to load services.'); } }
  useEffect(() => { http.get('/membership-plans/admin-catalog').then(r => setData(r.data)).catch(() => setError('Unable to load services.')); }, []);
  function open(service?: Service) { setEditing(service ?? null); setForm(service ? { organizationId: service.organizationId, name: service.name, shortName: service.shortName, isActive: service.isActive } : { organizationId: '', name: '', shortName: '', isActive: true }); }
  async function save() { try { if (editing) await http.put(`/membership-plans/services/${editing.id}`, form); else await http.post('/membership-plans/services', form); setEditing(undefined); await load(); } catch { setError('Unable to save service.'); } }
  return <><PageHeader title="Services" subtitle="Manage the activities that can be included in membership plans." />{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Button variant="contained" onClick={() => open()}>Create service</Button><Stack spacing={2} sx={{ mt: 3 }}>{data.services.map(s => <Card key={s.id}><CardContent sx={{ display: 'flex', justifyContent: 'space-between' }}><div><Typography variant="h6">{s.name}</Typography><Typography color="text.secondary">{s.organizationName} · {s.shortName} · {s.isActive ? 'Active' : 'Inactive'}</Typography></div><Button onClick={() => open(s)}>Manage</Button></CardContent></Card>)}</Stack>
    <Dialog open={editing !== undefined} onClose={() => setEditing(undefined)} fullWidth><DialogTitle>{editing ? 'Manage service' : 'Create service'}</DialogTitle><DialogContent><Stack spacing={2} sx={{ mt: 1 }}><FormControl required><InputLabel>Organization</InputLabel><Select label="Organization" value={form.organizationId} onChange={e => setForm({ ...form, organizationId: e.target.value })}>{data.organizations.map(o => <MenuItem key={o.id} value={o.id}>{o.name}</MenuItem>)}</Select></FormControl><TextField required label="Name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/><TextField required label="Short name" value={form.shortName} onChange={e => setForm({ ...form, shortName: e.target.value })}/><FormControlLabel control={<Checkbox checked={form.isActive} onChange={e => setForm({ ...form, isActive: e.target.checked })}/>} label="Active" /></Stack></DialogContent><DialogActions><Button onClick={() => setEditing(undefined)}>Cancel</Button><Button variant="contained" onClick={save}>Save</Button></DialogActions></Dialog></>;
}
